### PR TITLE
allow proxy display name to be used in player lines

### PR DESCRIPTION
**Pull request by intangir**
please allow option, change the bind name if you want, but i need a way to use the proxy display name rather than the bukkit names or raw name while using the bukkit bridge

### CODE REVIEW

**Comment by CodeCrafter47** [comment]
As of version 2.6.0 config file will work differently. See #113 for more information. ae6888f6084b72cd99ea148359d7f794fec80d01 should add what you want.

**Comment by intangir** [comment]
cool

**Comment by intangir** [comment]
do you have some examples of where to use this new config anywhere? i can't figure out the tablists..

**Comment by CodeCrafter47** [comment]
https://gist.github.com/CodeCrafter47/4181d55dca55aaf8a17dd33eb9bfbca6

**Pull request closed without merging**
