### PR TITLE
First steps towards Velocity support!

### LINKED ISSUE #405: Velocity Support?
Would it be possible to add support for [Velocity](https://www.velocitypowered.com/) at some point?

### PR DESCRIPTION
**Pull request by Andre601**
This PR will try to implement the long requested Velocity support to BungeeTabListPlus!

It is still WIP and by no means done or even in a ready state (See the "Current issue" section), but I try to work on it regularly.
Feel free to help by PRing stuff to the `feature/add-velocity-support` branch on my fork.

Closes #405 

## To Do
- [x] Velocity-side BTLP API
- [ ] Bootstrap Velocity
- [ ] Velocity plugin
- [ ] Velocity Module for Minecraft-data-api (requires separate PR)

## Current issues
- There seems to be issues with gradle not recognizing the `bungeetablistplus-api-velocity` module as such despite it being displayed like that in the IDE. I probably have to delete and recreate it to fix the issue... \*sigh*

### CODE REVIEW

**Comment by DevScyu** [comment]
You're missing two more lines in the settings.gradle file:
```diff
diff --git a/settings.gradle b/settings.gradle
index e781051d..17f1924a 100644
--- a/settings.gradle
+++ b/settings.gradle
@@ -33,12 +33,14 @@ project(':bungee-plugin').projectDir = file('bungee')
 project(':bungee-compat').projectDir = file('bungee_compat')
 project(':waterfall-compat').projectDir = file('waterfall_compat')
 project(':bukkit-plugin').projectDir = file('bukkit')
+project(':velocity-plugin').projectDir = file('velocity')
 project(':bungeetablistplus-common').projectDir = file('common')
 project(':BungeeTabListPlus').projectDir = file('bootstrap-bungee')
 project(':BungeeTabListPlus_BukkitBridge').projectDir = file('bootstrap-bukkit')
 project(':bungeetablistplus-api-bukkit').projectDir = file('api-bukkit')
 project(':bungeetablistplus-api-bungee').projectDir = file('api-bungee')
 project(':bungeetablistplus-api-sponge').projectDir = file('api-sponge')
+project(':bungeetablistplus-api-velocity').projectDir = file('api-velocity')
 project(':BungeeTabListPlus_SpongeBridge').projectDir = file('sponge')
 project(':example:example-bungee-api').projectDir = file('example/bungee')
 project(':example:example-bukkit-api').projectDir = file('example/bukkit')
```

**Comment by andreasdc** [comment]
Oh cool, maybe migrating to Velocity will be possible in that way. :D

**Comment by Andre601** [comment]
Yeah. Unfortunately will this not become a thing, as Velocity has quite a lot of differences that I can't just find workarounds for... At least some that wouldn't require work on some of the modules imported into BTLP...

Honestly, closing this. Maybe in the future, but not now.

**Comment by andreasdc** [comment]
> Yeah. Unfortunately will this not become a thing, as Velocity has quite a lot of differences that I can't just find workarounds for... At least some that wouldn't require work on some of the modules imported into BTLP...
> 
> Honestly, closing this. Maybe in the future, but not now.

Maybe contact Velocity's devs? They will add some features probably.

**Pull request closed without merging**
