### PR TITLE
Fix an issue related to 1.8.8 connections.

### PR DESCRIPTION
**Pull request by PrinceBunBun981**
Fixes: https://github.com/CodeCrafter47/BungeeTabListPlus/issues/739

Could possibly change the `0` to `-1`, but for simplicity sake, it's pretty much how it was before using https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/Either.java

### CODE REVIEW

**Comment by PrinceBunBun981** [comment]
image

Tested using same proxy, server, and client as https://github.com/CodeCrafter47/BungeeTabListPlus/issues/739:
Proxy: https://github.com/PaperMC/Waterfall/commit/9ac9f375b16305ab5bf0c2e52d1be12dbf9aec80 - Latest b552
Server: Paper 1.8.8 b445 https://api.papermc.io/v2/projects/paper/versions/1.8.8/builds/445/downloads/paper-1.8.8-445.jar
Client: Default 1.8.8

**Comment by andreasdc** [comment]
It looks to be a nice work, I would test it, but building this is pain in the...

**Review by MacTh3Mac — COMMENTED** [review]
Successfully compiled locally on MacOS 
AdoptOpenJDK-16.0.1+9

Proxy-  Waterfall Build 522.
Backend - 1.12.2, 1.16.5, 1.18.2, 1.20.1, 1.20.2
Tested with clients 1.12.2 Vanilla, 1.12.2 Optifine, 1.20.1 Vanilla, 1.20.2 Vanilla 

All load, display server specific and global tab lists and allow gameplay without error

**Comment by andreasdc** [comment]
> Successfully compiled locally on MacOS AdoptOpenJDK-16.0.1+9
> 
> Proxy- Waterfall Build 522. Backend - 1.12.2, 1.16.5, 1.18.2, 1.20.1, 1.20.2 Tested with clients 1.12.2 Vanilla, 1.12.2 Optifine, 1.20.1 Vanilla, 1.20.2 Vanilla
> 
> All load, display server specific and global tab lists and allow gameplay without error
> 
>  

I'm trying to setup this since 2/3 hours, getting different errors, now I'm stuck with:
`Could not determine the dependencies of task ':BungeeTabListPlus:shadowJar'.
> Could not resolve all dependencies for configuration ':BungeeTabListPlus:runtimeClasspath'.
   > Could not find de.codecrafter47.taboverlay:taboverlaycommon-config:1.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://nexus.codecrafter47.dyndns.eu/content/repositories/public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://nexus.codecrafter47.dyndns.eu/content/repositories/public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.codemc.org/repository/maven-public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.codemc.org/repository/maven-public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.md-5.net/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.md-5.net/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.spongepowered.org/maven/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.spongepowered.org/maven/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://jitpack.io/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
     Required by:
         project :BungeeTabListPlus > project :bungee-plugin
`
Can you share your JAR by any chance?

**Comment by andreasdc** [comment]
I confirm that this patch fixes the problem. Great job man!

**Comment by electronicboy** [comment]
The reality is that most components end up with formatting stuff inside of them, but, I would probably suggest using -1, just for the sake of consistency, unless there is a reason they opted for 0 in the past (which, I doubt, i'd imagine it's pretty much just a case of it having literally 0 impact for the most part)

**Comment by PrinceBunBun981** [comment]
> The reality is that most components end up with formatting stuff inside of them, but, I would probably suggest using -1, just for the sake of consistency, unless there is a reason they opted for 0 in the past (which, I doubt, i'd imagine it's pretty much just a case of it having literally 0 impact for the most part)

Building it with `-1` instead of `0` works fine as well, I had just opted to use the same logic CodeCrafter had prior to the changes. If anything, he can request changes to the PR or just change it himself if he wants `-1` to be used instead.

**Comment by andreasdc** [comment]
> > The reality is that most components end up with formatting stuff inside of them, but, I would probably suggest using -1, just for the sake of consistency, unless there is a reason they opted for 0 in the past (which, I doubt, i'd imagine it's pretty much just a case of it having literally 0 impact for the most part)
> 
> Building it with `-1` instead of `0` works fine as well, I had just opted to use the same logic CodeCrafter had prior to the changes. If anything, he can request changes to the PR or just change it himself if he wants `-1` to be used instead.

Is there any difference in the code behaviour?

**Pull request merged**
